# Generated by Django 3.0.5 on 2020-12-29 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0016_auto_20201228_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crontabschedule',
            name='name',
            field=models.CharField(default='', help_text='Short Name For This Crontab', max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='intervalschedule',
            name='name',
            field=models.CharField(default='', help_text='Short Name For This IntervalSchedule', max_length=200, verbose_name='Name'),
        ),
    ]
